---
title: "About"
---

SKY's vision is to leverage the wonderful opportunities of the digital age in order to make science more Accessible, Open, Collaborative, Effective and Credible.  

SKY ambitions to transform the way we do and share research in the social sciences by:

* Accumulating all individual research results into a summarized state of knowledge for each important research question, mostly using meta-analysis tools.
* Providing a clear status of what is known and what is not known in order to help researchers select and coordinate on the most important research projects, funders to allocate funds and policy-makers, journalists and citizens to assess the credibility, precision and breadth of knowledge on a given question.
* Providing an up-to-date source of econometric and statistical tools, as well as a list of open methodological isues and forums where these questions are tackled collectively.
* Providing an environment to transparently register every step made on a research project (lab notes).

SKY ambitions to fight the evils of the current scientific system:

* Closed access 
* Publication bias and specification search
* Questionable Research Practices
* Lack of publication of Null results
* Lack of large collaborative initiatives 
* Lack of replication

Important documentation:

* The most updated set of [rules of the game](ROG.html) for contributing to SKY.
* A [tutorial](tuto.html) guiding you step by step on how to contribute to SKY.
* A more extensive [description](https://economistjourney.blogspot.com/2019/03/sky-tool-for-decentralized-accumulation.html) of the motivations behing SKY, how it works and how to contribute to it. 


Test