---
title: "Are Forest Conservation Programs a Cost-Effective Way to Fight Climate Change?"
---

Cutting down standing forest sends GHGs in the atmosphere, especially when the forest is replaced by crops.
As a consequence, programs that pay landowners not to cut their standing forest might be an effective way to combat climate change, if they succeed in maintaining enough standing forest for a reasonbable amount of money.

This article preregisters a meta-analysis aiming at gathering published estimates of the impact of Forest Conservation Programs on the amounf of standing forest.

We have already conducted an extensive search of the published databases, to be described.

We have identified around 12 publications providing a causal estimate of the additional effect of a forest conservation program.
We have converted all estimates in percentage points of saved forest area per year.
We are going to conduct first a meta-analysis of the additionality parameter.
We have collected data on program costs, so that we are able to form cost-effectiveness estimates.
We are also going to compute cost-benefit estimates. 
Key for these estimates is the benefit estimates.
They depend on the durability of the program effects.
We plan to follow Jayachandran et al (2018) middle scenario for durability of the program impacts.

Each estimate will be conducted using both fixed and randomo effects models.

We plan to control for:

* Whether the estimate is from an RCT, an observational method or a natural experiment.
If impossible to separate, we plan to regroup the last two components.
* Whether the estimate comes from developed or developing countries, and, if feasible, South America, Africa or Asia.
* Whether payments were based on actual measurements, or whether there were only randomized controls, and whether the controls where in person, by satelllite or by aerial photo.
It is not sure that we can build the variable for these last categories.



