---
title: "Social Science Knowledge Accumulation Initiative"
---

This is the website for the Social Science Knowledge Accumulation Initiative or SKY.
SKY ambitions to transform the way we do and share research in the social and biomedical sciences by:

* Accumulating all individual research results into a summarized state of knowledge for each important research question, mostly using meta-analaysis tools.
* Providing a clear status of what is known and what is not known in order to help researchers select and coordinate on the most important research projects, funders to allocate funds and policy-makers, journalists and citizens to assess the credibility, precision and breadth of knowledge on a given question.
* Assessing the quality and scope of individual and collective research contributions, by measuring the contribution of individual research projects to accumulated knowledge, but also quantifying the amount of publication bias and specification search bias that a particular researcher or research team, or journal or editor has.
* Providing an up-to-date source of econometric and statistical tools, as well as a list of open methodological isues and forums where these questions are tackled collectively.
* Providing an environment to transparently register every step made on a research project (lab notes).
* Providing an up-to-date list of accepted results in most fields, to be used for introductory lectures.

SKY's vision is to leverage the wonderful opportunities of the digital age in order to make science collaborative, open and freely accessible to all. 

SKY ambitions to fight the evils of the current scientific system:

* Closed access 
* Publication bias and specification search
* Questionable Research Practices
* Lack of publication of Null results
* Lack of large collaborative initiatives 
* Lack of replication

In our vision, SKY is destined to replace all journals and to be a place where all collaborative research projects start and are conducted.

For the moment, you can find a series of [meta-analysis](meta.html) and an introduction to [the econometrics of causal inference](inference.html).