---
title: "Evidence on the Effectiveness of Social Interventions"
---

SKY hosts for the moment preliminary answers to several questions relative to the effectiveness of social interventions:

* Environment 
    + [What are the Most Cost-Effective Ways to Fight Climate Change?](CC.html)
    + [What are the Economic Consequences of Climate Change?](ECCC.html)
    + [Are Nudges a Cost-Effective Way to Change Environmental Behavior?](nudges.html)
    + [Are Nudges a Cost-Effective Way to Promote Enrollment into Payments for Environmental Services?](https://chabefer.github.io/SKAI_Nudges_PES/)
* Education
    + [Are Job Training Programs Effective?](JTP.html)
    + [Are Socio-Emotional Learning Programs Effective?](SEL.html)
    + [Are Growth-Mindset Interventions Effective?](GM.html)
    + [Are Mindfulness-based Interventions Effective?](MM.html)
    + [What are the Economic Returns to Education?](ERtE.html)
* Health
    + [Does Exercise Improve Health Outcomes in Old Age?](EH.html)
    + [What are the Consequences of Lead Poisoning?](Lead.html)
    + [Do BTX injections decrease depression?](https://nicholas-coles.shinyapps.io/OpenMetaPipeline_Ver2/)
* Development
    + [Are Conditional Cash Transfers Programs Effective?](CCT.html)
    + [Are Unconditional Cash Transfers Programs Effective?](UCT.html)
    + [Are Micro-Credit Programs Effective?](MC.html)
* Crime
    + [Are Cognitive Behavioral Therapies Effective?](CBTC.hml)
    + [Are Ban the Box Policies Effective?](BtB.html)
 



