---
title: "Are Nudges a Cost-Effective Way to Change Environmental Behavior?"
---

*This article is a stub.*
*Do not hesitate to substantiate.*

[Nudges](https://en.wikipedia.org/wiki/Nudge_theory) are non-monetary interventions leveraging on the psychological motives of agents to alter their behavior in what is hoped to be a socially beneficial way.
Nudges are more and more used for as environmental interventions, as an alternative to more traditional economic instruments such as taxes, quotas, subsidies or regulations.

The first (to our knowledge) meta-analysis of the impact of nudges on environmental behavior can be found [here](https://doi.org/10.1016/j.enpol.2013.05.109).
The Working Paper version can be found [here](https://www.ioes.ucla.edu/wp-content/uploads/delmas-fischlein-asensio.pdf) 
The database is not online, to our knowledge.
The study does not seem to contain tests for publication bias.

A publically accessible (but probably less complete) list of estimates of the impact of nudges can be found [here](https://docs.google.com/spreadsheets/d/15hxgnY7ITJ_8jarvq_NAaFQaFYLc7ABsYrLKKewyBdo/edit?usp=sharing).
It remains to analyze this dataset using meta-analytical tools.
Also, each individual study needs a separate SKY page so that the details of the computations are apparent.

