---
title: "Rules of the Game on SKY"
---

### Be bold 

Do not hesitate to create new questions and to feed them the little information that you have. If it is nothing, then that’s fine. Just ask the question.

### Do not strive for perfection at first

A stub, a line, a link, a back of the enveloppe estimate are better than nothing. 
Others or yourself later will complete your work.

### Act in god faith

When interpreting evidence and discussing results, be open to arguments. 

### Assume good faith

Be civil, be tolerant: errors and mistakes happen. 
They most of the time come in good faith.

### Use data to settle disputes

Data is the ultimate settler of scientific disputes.
If various interpretations of the same data can be held, mention them and mention which tests might be able to settle between them. 
When discussing methods, use theory, simulations or performance on real data to come to an agreement. 

### Do not proselytise

If you’re coming on SKY only to make a point, whatever the evidence, you’ll be frowned upon. 
Accept that some people are not convinced by the same evidence than you are, try to understand why and try to find a way to answer them or at least delineate the possible concurrent interpretations and how we could go about deciding between them.

### Do not violate copyright 

When mentioning a published paper, always provide links to the published version. 
It's fair to also provide a link to a freely accessible pre-print. 
If you quote from the paper, use quotation marks or the quotation environment. 
Refrain from extracting a figure or a table from a paper. 
Simply provide the link to it on the publisher webpage. 
I'm in discussion with publishers in order to understand the rules of the game. 

What seems totally fair game: extract the main result from the paper and build a figure or a table with it.
Put the data online (either GoogelDoc, but preferably SKY's MySQL repo).